version: "3.9"
services:
  nats:
    image: nats:2-alpine
    ports: ["4222:4222"]
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: corpchat
      POSTGRES_USER: chat
      POSTGRES_PASSWORD: chat123
    ports: ["5432:5432"]
    volumes: ["./db:/var/lib/postgresql/data"]
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  server:
    build: ../backend
    env_file: .env
    depends_on: [db, redis, nats]
    ports: ["8080:8080"]
    command: ["./corpchat-server"]
  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes: ["./minio:/data"]
  app:
    build:
      context: ../web/corpchatt
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
      - db